//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int product_code { get; set; }
        public string product_name { get; set; }
        public string product_description { get; set; }
        public double product_price { get; set; }
        public int product_stock_count { get; set; }
        public Nullable<int> product_category_id { get; set; }
    }
}
