//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int sale_id { get; set; }
        public Nullable<int> product_code { get; set; }
        public Nullable<int> sale_count { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
    }
}
